# Generated by Django 4.1 on 2022-11-04 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviso_title', models.CharField(blank=True, max_length=128, null=True)),
                ('media_content', models.CharField(blank=True, max_length=256)),
                ('content', models.TextField(blank=True, max_length=256)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacao_title', models.CharField(blank=True, max_length=64)),
                ('ocupacao_picture', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_title', models.CharField(blank=True, max_length=64)),
                ('setor_picture', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_picture', models.CharField(blank=True, max_length=256)),
                ('ocupacao', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocupacao', to='api.ocupacao')),
                ('setor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='setor', to='api.setor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aviso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('aviso', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=256)),
                ('data', models.DateField(auto_now_add=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aviso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aviso',
            name='likes',
            field=models.ManyToManyField(through='api.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aviso',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.userprofile'),
        ),
    ]
